services:
  postgres:
    image: postgres:16-alpine
    container_name: rockib_ia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rockib
      POSTGRES_PASSWORD: rockib_dev_password
      POSTGRES_DB: rockib_ia
    ports:
      - "5432:5432"
    volumes:
      - rockib_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rockib_ia_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - rockib_redis_data:/data

volumes:
  rockib_pg_data:
  rockib_redis_data:
